steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/asset-alchemy-api:$COMMIT_SHA"
      - "--build-arg"
      - "_AUTH0_DOMAIN=asset-alchemy-staging.us.auth0.com"
      - "--build-arg"
      - "_AUTH0_API_IDENTIFIER=https://api.assetalchemy.io"
      - "--build-arg"
      - "_IEX_API_KEY=IEX_API_KEY"
      - "--build-arg"
      - "_USER_COLLECTION=users-staging"
      - "."
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/asset-alchemy-api:$COMMIT_SHA"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "asset-alchemy-api-staging"
      - "--image"
      - "gcr.io/$PROJECT_ID/asset-alchemy-api:$COMMIT_SHA"
      - "--region"
      - "nam5"
images:
  - "gcr.io/$PROJECT_ID/asset-alchemy-api:$COMMIT_SHA"
availableSecrets:
  secretManager:
    - versionName: projects/asset-alchemy/secrets/IEX_API_KEY_PROD/versions/latest
      env: "IEX_API_KEY"
